const PAGES = {
  home: '/home',
  patientFinding: '/patient-finding',

  analytics: '/analytics',
  statistics: '/statistics',

  profileOverview: '/profile/profile-overview',
  profileSetting: '/profile/settings',
  profilePassword: '/profile/change-password',
  patients: '/patients',

  users: '/users',
  hospital: '/hospital',
  hospitalDetail: '/hospital-detail',
  department: '/department',
  departmentDetail: '/department-detail',
  job: '/job',
  jobDetail: '/job-detail',
  company: '/company',
  companyDetail: '/company-detail',
  township : '/township',
  townshipDetail : '/township-detail',
  project: '/project',
  projectDetail: '/project-detail',
  projectInformation: '/projectInformation',
  projectInformationDetail: '/projectInformation-detail',
  newUser: '/users/new-user',
  newHospital: '/hospitals/new-hospital',
  newDepartment: '/departments/new-department',
  newJob: '/jobs/new-job',
  newCompany: '/companies/new-company',
  newTownship: '/townships/new-township',
  newProject: '/projects/new-project',
  newProjectInformation: '/projectInformations/new-projectInformation',
  newAssessment: '/assessment/new-assessment',
  newFinding: '/finding-structure/new-finding',
  editFinding: '/finding-structure/edit-finding',
  newReferences: '/references/new-references',
  newManufacturerDicom: '/manufacturer-dicom/new-manufacturer-dicom',
  newSettings: '/settings/new-settings',
  editUser: '/users/edit-user',
  editHospital: '/hospitals/edit-hospital',
  editDepartment: '/departments/edit-department',
  editJob : '/jobs/edit-job',
  editCompany: '/companies/edit-company',
  editTownship: '/townships/edit-township',
  editProject: '/projects/edit-project',
  editProjectInformation: '/projectInformations/edit-projectInformation',
  editReferences: '/references/edit-references',
  editManufacturerDicom: '/manufacturer-dicom/edit-manufacturer-dicom',
  editAssessment: '/assessment/edit-assessment',
  editSettings: '/settings/edit-settings',
  changepassword: '/account-settings/changepassword',
  editExam: '/patients/exams/edit-exam',

  sessions: '/sections',
  references: '/references',
  manufacturerDicom: '/manufacturer-dicom',
  exportData: '/export-data',
  settings: '/settings',
  findingStructure: '/finding-structure',
  assessment: '/assessment',
  parameters: '/parameters',
  python: '/scripts',
  newPython: '/new-script',

  // not auth
  signIn: '/sign-in',
  signUp: '/sign-up',
};

export default PAGES;
