export const exportData = {
  items: [
    {
      id: 1,
      studyRef: 'String',
      typeOfData: 'String',
      mainParameterCV: 'String',
      mainParameterCSD: 'String',
      mainParameterCM: 'String',
      findingSite: 'String',
      imageView: 'String',
      imageMode: 'String',
      cardiacCyclePoint: 'String',
      respiratoryCyclePoint: 'String',
      directionOfFlow: 'String',
      measurementMethod: 'String',
      measurementUnit: 'String',
      resultValue: 'String',
      derivation: 'String',
      selectionStatus: 'String',
      observationCV: 'String',
      observationCSD: 'String',
      observationCM: 'String',
      observationSetCV: 'String',
      observationSetCSD: 'String',
      observationSetCM: 'String',
      assessmentCV: 'String',
      assessmentCSD: 'String',
      assessmentCM: 'String',
      assessmentTypeCV: 'String',
      assessmentTypeCSD: 'String',
      assessmentSetCV: 'String',
      assessmentSetCSD: 'String',
      assessmentSetCM: 'String',
      iCDMainCode: 'String',
      iCDSubCode: 'String',
      iCDCM: 'String',
      createdAt: 'String',
    },
  ],
  limit: 10,
  page: 0,
  totalItems: 10,
  totalPages: 1,
};
